### ISSUE TITLE
Integrate Dark Mode

### ISSUE THREAD

**Issue by opeolluwa** [opeolluwa/FileSync#126] opened 2023-06-11 10:09 UTC
Integrate the application dark Mode using this color palette and [TailwindCSS convection](https://tailwindcss.com/docs/dark-mode)
![Screenshot from 2023-06-11 11-00-42](https://github.com/opeolluwa/send-file/assets/67811147/9d5ac04f-a8bc-4a1f-9658-a1a3df05dba6)

To do this, extend [tailwind.config.cjs](https://github.com/opeolluwa/send-file/blob/master/tailwind.config.cjs) with the theme, immediately after the [default color theme](https://github.com/opeolluwa/send-file/blob/master/tailwind.config.cjs#L18) 

the color theme may be used alongside the TailwindCSS gray color, especially for styling text. 
```js

'app-dark':{ 
 DEFAULT: '#18122B', 
 50: '#907DC9',
  100: '#836FC3', 
 200: '#6A52B7',
  300: '#58429E', 
 400: '#483681', 
 500: '#382A65',
  600: '#281E48', 
 700: '#18122B', 
 800: '#020103', 
 900: '#000000', 
 950: '#000000'
},
```

**Comment by Keith-Web3** [comment] 2023-09-03 19:12
Hello Opeoluwa, can I be assigned this issue? I would love to contribute to this project!

**Comment by opeolluwa** [comment] 2023-09-03 19:45
Sure thing!

**Comment by Keith-Web3** [comment] 2023-09-06 17:26
Good day Ope 👋. I tried installing yarn on my device to no avail, seems I'm missing something. You can unassign me from the issue for now so other contributors can have a go at it. I'll continue trying to install yarn and if I'm successful while the issue is still open and unassigned, I'll raise a pull request, thanks.

**Comment by opeolluwa** [comment] 2023-09-07 16:26
have you tried `npm i -g yarn`?

**Comment by Keith-Web3** [comment] 2023-09-08 19:46
No, saw a different way of installing it but I'll try this now.

**Closed** 2023-09-18 20:08 UTC
